# Export IDL files needed by users of the public headers to compile their
# own interfaces with qaic
fastrpc_idldir = $(includedir)/fastrpc
dist_fastrpc_idl_DATA = \
	AEEStdDef.idl \
	AEEStdErr.idl \
	remote.idl

EXTRA_DIST = \
	adsp_current_process.idl \
	adsp_current_process1.idl \
	adsp_default_listener.idl \
	adsp_default_listener1.idl \
	adsp_listener.idl \
	adsp_listener1.idl \
	adsp_perf.idl \
	adsp_perf1.idl \
	adspmsgd_adsp.idl \
	adspmsgd_adsp1.idl \
	adspmsgd_apps.idl \
	apps_mem.idl \
	apps_remotectl.idl \
	apps_std.idl \
	dspqueue_rpc.idl \
	remotectl.idl \
	remotectl1.idl
