name: Nightly Kernel Build

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Linux Kernel Source
        run: |
          git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux

      - name: Build Linux Kernel
        run: |
          cd linux
          umask 0022
          make LLVM=1 ARCH=arm64 defconfig
          make LLVM=1 ARCH=arm64 -j$(nproc) dir-pkg INSTALL_MOD_STRIP=1

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel-artifacts
          path: |
            linux/arch/arm64/boot/Image
            linux/arch/arm64/boot/dts/qcom/**
            linux/tar-install/**
