name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: install auto tools
      run: |
        sudo apt-get install automake
    
    - name: Download Android NDK and unzip 
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r27-linux.zip
        unzip -q android-ndk-r27-linux.zip

    - name: Create softlink files for the compiler, linker and other tools
      run: |
        pwd
        export ANDROID_NDK_HOME="$PWD/android-ndk-r27" 
        export PATH="$PATH:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/"        
        export CC=aarch64-linux-android34-clang
        export CXX=aarch64-linux-android34-clang++
        export AS=llvm-as
        export LD=ld
        export RANLIB=llvm-ranlib
        export STRIP=llvm-strip

    - name: provide permissions and compile
      run: |
        chmod 777 gitcompile
        make -v
        ./gitcompile --host=aarch64-linux-android
        cat config.log

