name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./gitcompile --host=aarch64-linux-android

    - name: Install dependencies
      run: sudo make install

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck


