name: pre_merge
description: |
  This workflow defines the pre_merge CI process for the fastrpc repository.
  It is triggered on pushes to 'main' or 'development' branches,
  on pull request events (opened, synchronize, reopened) targeting 'main' or 'development',
  or manually via workflow_dispatch.
  Loading: Loads the build matrix from MACHINES.json.
  Build: Syncs and Builds code for each machine/firmware pair using sync_build.yml.
  Test: Runs LAVA tests using built artifacts via test.yml.
  All jobs use reusable workflows and inherit secrets from the caller.

on:
  push:
    branches:
    - 'main'
    - 'development'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - 'main'
    - 'development'
  workflow_dispatch:

jobs:

  # The loading job will load the build matrix from MACHINES.json
  loading:
    uses: qualcomm/fastrpc/.github/workflows/loading.yml@development
    secrets: inherit

  # Each job in build and test will run for every {machine, firmware} pair
  # The build job will run on the machines specified in the build_matrix output
  # from the loading job. It will use the build.yml workflow to build the code.
  build:
    needs: loading
    strategy:
      matrix:
        include: ${{ fromJSON(needs.loading.outputs.build_matrix) }}
    uses: qualcomm/fastrpc/.github/workflows/sync_build.yml@development
    secrets: inherit
    with:
      docker_image: fastrpc-image:latest
      machine: ${{ matrix.machine }}
      firmware: ${{ matrix.firmware }}

  # The test job will run on the machines specified in the full_matrix output
  # from the loading job. It will use the test.yml workflow to run tests.
  test:
    needs: [loading, build]
    uses: qualcomm/fastrpc/.github/workflows/test.yml@development
    secrets: inherit
    with:
      docker_image: fastrpc-image:latest
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      full_matrix: ${{ needs.loading.outputs.full_matrix }}
