name: Prevent pull request to main
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.head_ref }} != "development" ] && [ ${{ github.base_ref }} == "main" ]; then
            echo "Create a pull request to quic/development branch"
            echo "Pull requests to main branch are only allowed from quic/development branch."
            exit 1
          fi